name: 'Setup tarantool'
description: 'Setup tarantool environment with caching'
branding:
  icon: 'code'
  color: 'red'
inputs:
  tarantool-version:
    description: Tarantool version
  nightly-build:
    description: Whether to install a nightly build
    required: false
    default: false
  cache-key:
    description: Deprecated. Custom key used for APT packages caching
    required: false
runs:
  using: 'node16'
  main: dist/index.js
