name: Test in docker

on:
  push:

jobs:
  test:
    runs-on: ['ubuntu-22.04']

    strategy:
      fail-fast: false
      matrix:
        tarantool:
          - '1.10'
          - '2.10'
          - '2.11'

        image:
          - ubuntu:focal
          - ubuntu:jammy
          - debian:buster
          - debian:bullseye

        # Only 2.11 is available on debian bookworm
        include:
          - tarantool: '2.11'
            image: debian:bookworm

    container:
      image: ${{ matrix.image }}

    env:
      TARANTOOL_CACHE_KEY_SUFFIX: -DA-${{ matrix.image }}-${{ github.run_id }}
      DEBIAN_FRONTEND: noninteractive

    steps:
      - name: Configure apt-get
        run: |
          mkdir -p /etc/apt/apt.conf.d
          printf '%s\n%s\n'                    \
            'APT::Install-Recommends "false";' \
            'APT::Install-Suggests "false";'   \
            > /etc/apt/apt.conf.d/no-recommends-no-suggests.conf

      - name: Update repositories metadata
        run: |
          apt-get -y update

      - name: Workaround interactive tzdata configuration problem (gh-50)
        run:
          apt-get -y install tzdata

      - name: Install setup-tarantool dependencies
        run: |
          apt-get -y install sudo lsb-release gnupg ca-certificates rsync

      # Bring `node` executable file into PATH for latest-version
      # and verify-versions actions.
      #
      # It is not needed for a usual usage of the setup-tarantool
      # action within a container job, because GitHub Action
      # runner mounts a volume with a `node` executable into the
      # container.
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: actions/checkout@v4

      - id: latest-version
        uses: ./.github/actions/latest-version
        with:
          tarantool-series: '${{ matrix.tarantool }}'

      - name: Setup from scratch
        uses: ./
        with:
          tarantool-version: ${{ matrix.tarantool }}

      - name: Check precise version
        uses: ./.github/actions/verify-version
        with:
          tarantool-version: '${{ steps.latest-version.outputs.git-describe }}'
          from-cache: false

      - name: Uninstall tarantool
        run: sudo apt-get -y remove tarantool tarantool-dev tarantool-common

      - name: Setup from cache
        uses: ./
        with:
          tarantool-version: ${{ matrix.tarantool }}

      - name: Verify install from cache
        uses: ./.github/actions/verify-version
        with:
          tarantool-version: '${{ steps.latest-version.outputs.git-describe }}'
          from-cache: true
